### ISSUE TITLE
Pull request workflow

### ISSUE THREAD

**Issue by clarkd** [leekelleher/umbraco-cloud-toolkit#2]
This might not be the right place to ask this, but I know you guys might have a few ideas for me...

We've recently had an Umbraco Cloud site built for us by an agency which we're now taking in house and as such I've recently setup the appropriate Bitbucket repository alongside the Umbraco Cloud git repo.

I'm struggling to understand how a normal pull request workflow fits into the picture. I currently have the C# code in the BB repo and hence a pull request can take place there - but how would you then look to take the build output (DLL) and get that into the Umbraco repository. And on top of that, if we wanted to pull the JS/CSS/Views into the BB repository, we'd need a way of moving those into the right place at build/deploy time. 

The Umbraco git model seems to work well for simple uses cases but for a larger development team, it doesn't seem to fit into a common enterprise engineering workflow.

Any thoughts?

**Comment by leekelleher** [comment]
@clarkd - thanks for posting your question, but this repository is for a specific package, not for general Umbraco Cloud support. Your question might be better answered in the Umbraco Cloud section of the community forum? <https://our.umbraco.org/forum/umbraco-cloud/>

I do hear your frustrations with the development workflow for Umbraco Cloud.  There is some documentation on the community site about how to work with Cloud and Visual Studio: <https://our.umbraco.org/Documentation/Umbraco-Cloud/Set-Up/Visual-Studio/>

Ultimately, there's a fair amount of trial and error, until you find a happy medium with the process.
(_I'm still exploring various deployment workflows myself_)

**Comment by clarkd** [comment]
Hi Lee, thanks for the few links.

I'll take a look at posting on the forum.

Are you able to share any of pros/cons of the workflows you've experimented
with?

On 22 Feb 2017 12:18 am, "Lee Kelleher" <notifications@github.com> wrote:

@clarkd <https://github.com/clarkd> - thanks for posting your question, but
this repository is for a specific package, not for general Umbraco Cloud
support. Your question might be better answered in the Umbraco Cloud
section of the community forum? https://our.umbraco.org/forum/umbraco-cloud/

I do hear your frustrations with the development workflow for Umbraco
Cloud. There is some documentation on the community site about how to work
with Cloud and Visual Studio: https://our.umbraco.org/
Documentation/Umbraco-Cloud/Set-Up/Visual-Studio/

Ultimately, there's a fair amount of trial and error, until you find a
happy medium with the process.
(*I'm still exploring various deployment workflows myself*)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/leekelleher/umbraco-cloud-toolkit/issues/2#issuecomment-281526103>,
or mute the thread

**Comment by clarkd** [comment]
@leekelleher I'll go ahead and close the issue as I've now posted over on the forums. If you do have some time to share your experiences that would be really helpful. Thanks.

https://our.umbraco.org/forum/umbraco-cloud/84170-pull-request-workflow
